apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-arc-controller
---
apiVersion: arcdata.microsoft.com/v3
kind: DataController
metadata:
  generation: 1
  name: arc-dc
spec:
  credentials:
    controllerAdmin: controller-login-secret
    dockerRegistry: arc-private-registry
    serviceAccount: sa-arc-controller
  docker:
    imagePullPolicy: Always
    imageTag: v1.4.0_2022-02-25
    registry: mcr.microsoft.com
    repository: arcdata
  infrastructure: onpremises 
  security:
    allowDumps: true #Set this to false if deploying on OpenShift
    allowNodeMetricsCollection: true #Set this to false if deploying on OpenShift
    allowPodMetricsCollection: true #Set this to false if deploying on OpenShift
  services:
  - name: controller
    port: 30080
    serviceType: LoadBalancer # Modify serviceType based on your Kubernetes environment
  settings:
    ElasticSearch:
      vm.max_map_count: "-1"
    azure:
      connectionMode: indirect
      location: eastus # Choose a different Azure location if you want
      resourceGroup: arc_rg
      subscription: ce5a3eca-e3bb-4208-86e9-ae9f675f827f
    controller:
      displayName: arc-dc
      enableBilling: true
      logs.rotation.days: "7"
      logs.rotation.size: "5000"
  storage:
    data:
      accessMode: ReadWriteOnce
      className: portworx-sc
      size: 15Gi
    logs:
      accessMode: ReadWriteOnce
      className: portworx-sc 
      size: 10Gi
