apiVersion: v1
data:
  password: V2VsY29tZTEyMzQh
kind: Secret
metadata:
  name: pg1-login-secret
type: Opaque
---
apiVersion: arcdata.microsoft.com/v1beta2
kind: PostgreSql
metadata:
  name: pg1
spec:
  engine:
    version: 12
    extensions:
    - name: citus
  scale:
    workers: 3
  scheduling:
    default:
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
  services:
    primary:
      type: LoadBalancer # Modify service type based on your Kubernetes environment
  storage:
    backups:
      volumes:
      - className: portworx-sc
        size: 5Gi
    data:
      volumes:
      - className: portworx-sc 
        size: 5Gi
    logs:
      volumes:
      - className: portworx-sc 
        size: 5Gi
