apiVersion: v1
data:
  password: V2VsY29tZTEyMzQh
  username: YXp1cmV1c2Vy
kind: Secret
metadata:
  name: metricsui-admin-secret
type: Opaque
---
apiVersion: v1
data:
  password: V2VsY29tZTEyMzQh
  username: YXp1cmV1c2Vy
kind: Secret
metadata:
  name: logsui-admin-secret
type: Opaque
