apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRule
metadata:
  name: volume-resize
  namespace: portworx
spec:
  selector:
    matchLabels:
      app: arcsqlmi
      env: dev
  conditions:
    expressions:
    - key: "100 * (px_volume_usage_bytes / px_volume_capacity_bytes)"
      operator: Gt
      values:
      - "50"
  actions:
  - name: openstorage.io.action.volume/resize
    params:
      scalepercentage: "20"
      maxsize: "100Gi"
EOF